# Site settings
title: Felipe Fernandes
email: felipefernandesweb@gmail.com
description: "Das coisas que eu encontro nas minhas navegadas na web: tecnologia e entretenimento."
baseurl: ""
url: "http://felipefernandes.github.io"
twitter_username: felipefernandes
github_username:  felipefernandes

# Build settings
markdown: kramdown
permalink: pretty
